In [16]:
from transformers import BertTokenizer, BertForMaskedLM
from torch.nn import functional as F
import torch

### Masked Language Model

In [17]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased') 
# 사전 학습된 BERT 모델 불러오기 (case sensitive하지 않음)
# WordPiece 임베딩 기반

model = BertForMaskedLM.from_pretrained('bert-base-uncased', return_dict = True) 
# downstream task 관련 클래스
# MLM 모델, dic결과 return (어떤 단어를 masking 했는지)

text = "The capital of France, " + tokenizer.mask_token + ", contains the Eiffel Tower."
# [mask]=Paris

input = tokenizer.encode_plus(text, return_tensors = "pt")
# 텍스트의 다양한 특징을 추출
# pt - pythorch

Lock 2181257613128 acquired on C:\Users\ky_moon/.cache\huggingface\transformers\45c3f7a79a80e1cf0a489e5c62b43f173c15db47864303a55d623bb3c96f72a5.d789d64ebfe299b0e416afc4a169632f903f693095b4629a7ea271d5a0cf2c99.lock


Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Lock 2181257613128 released on C:\Users\ky_moon/.cache\huggingface\transformers\45c3f7a79a80e1cf0a489e5c62b43f173c15db47864303a55d623bb3c96f72a5.d789d64ebfe299b0e416afc4a169632f903f693095b4629a7ea271d5a0cf2c99.lock
Lock 2181781889224 acquired on C:\Users\ky_moon/.cache\huggingface\transformers\c1d7f0a763fb63861cc08553866f1fc3e5a6f4f07621be277452d26d71303b7e.20430bd8e10ef77a7d2977accefe796051e01bc2fc4aa146bc862997a1a15e79.lock


Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Lock 2181781889224 released on C:\Users\ky_moon/.cache\huggingface\transformers\c1d7f0a763fb63861cc08553866f1fc3e5a6f4f07621be277452d26d71303b7e.20430bd8e10ef77a7d2977accefe796051e01bc2fc4aa146bc862997a1a15e79.lock
Lock 2182501681032 acquired on C:\Users\ky_moon/.cache\huggingface\transformers\534479488c54aeaf9c3406f647aa2ec13648c06771ffe269edabebd4c412da1d.7f2721073f19841be16f41b0a70b600ca6b880c8f3df6f3535cbc704371bdfa4.lock


Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Lock 2182501681032 released on C:\Users\ky_moon/.cache\huggingface\transformers\534479488c54aeaf9c3406f647aa2ec13648c06771ffe269edabebd4c412da1d.7f2721073f19841be16f41b0a70b600ca6b880c8f3df6f3535cbc704371bdfa4.lock
Lock 2181662919112 acquired on C:\Users\ky_moon/.cache\huggingface\transformers\3c61d016573b14f7f008c02c4e51a366c67ab274726fe2910691e2a761acf43e.37395cee442ab11005bcd270f3c34464dc1704b715b5d7d52b1a461abe3b9e4e.lock


Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Lock 2181662919112 released on C:\Users\ky_moon/.cache\huggingface\transformers\3c61d016573b14f7f008c02c4e51a366c67ab274726fe2910691e2a761acf43e.37395cee442ab11005bcd270f3c34464dc1704b715b5d7d52b1a461abe3b9e4e.lock
Lock 2182502664328 acquired on C:\Users\ky_moon/.cache\huggingface\transformers\a8041bf617d7f94ea26d15e218abd04afc2004805632abc0ed2066aa16d50d04.faf6ea826ae9c5867d12b22257f9877e6b8367890837bd60f7c54a29633f7f2f.lock


Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Lock 2182502664328 released on C:\Users\ky_moon/.cache\huggingface\transformers\a8041bf617d7f94ea26d15e218abd04afc2004805632abc0ed2066aa16d50d04.faf6ea826ae9c5867d12b22257f9877e6b8367890837bd60f7c54a29633f7f2f.lock


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [23]:
print('text :', text)
print('[mask] :', tokenizer.mask_token)
print('input :', input)

text : The capital of France, [MASK], contains the Eiffel Tower.
[mask] : [MASK]
input : {'input_ids': tensor([[  101,  1996,  3007,  1997,  2605,  1010,   103,  1010,  3397,  1996,
          1041, 13355,  2884,  3578,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [24]:
mask_index = torch.where(input["input_ids"][0] == tokenizer.mask_token_id)
# 어떤 단어가 마스킹 되었는지 인덱스를 찾음

In [30]:
print(input['input_ids'][0])
print(tokenizer.mask_token_id)
print(mask_index)

tensor([  101,  1996,  3007,  1997,  2605,  1010,   103,  1010,  3397,  1996,
         1041, 13355,  2884,  3578,  1012,   102])
103
(tensor([6]),)


In [34]:
output = model(**input)  # 모델의 결과값
logits = output.logits  # 마스킹된 단어가 치환될 단어들의 확률 분포
softmax = F.softmax(logits, dim=-1)  # 소프트맥스 사용

In [38]:
mask_word = softmax[0, mask_index, :]
top_10 = torch.topk(mask_word, 10, dim = 1)[1][0]  # 소프트맥스에서의 상위 10개
for token in top_10:
   word = tokenizer.decode([token])
   new_sentence = text.replace(tokenizer.mask_token, word)
   print(new_sentence)

The capital of France, paris, contains the Eiffel Tower.
The capital of France, lyon, contains the Eiffel Tower.
The capital of France, lille, contains the Eiffel Tower.
The capital of France, toulouse, contains the Eiffel Tower.
The capital of France, marseille, contains the Eiffel Tower.
The capital of France, orleans, contains the Eiffel Tower.
The capital of France, strasbourg, contains the Eiffel Tower.
The capital of France, nice, contains the Eiffel Tower.
The capital of France, cannes, contains the Eiffel Tower.
The capital of France, versailles, contains the Eiffel Tower.


### Next Sentence Prediction

In [40]:
from transformers import BertTokenizer, BertForNextSentencePrediction
import torch
from torch.nn import functional as F

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForNextSentencePrediction.from_pretrained('bert-base-uncased') # NSP 모델

prompt = "The child came home from school."
next_sentence = "He played soccer after school."
encoding = tokenizer.encode_plus(prompt, next_sentence, return_tensors='pt')

outputs = model(**encoding)[0]
softmax = F.softmax(outputs, dim = 1)
print(softmax)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForNextSentencePrediction: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tensor([[0.9953, 0.0047]], grad_fn=<SoftmaxBackward>)


### Classification Model

In [43]:
from transformers import BertModel, BertForSequenceClassification
from torch import nn, optim
import torch
import os
from kobert_transformers import get_kobert_model

class PYBERTClassifier(nn.Module):
    '''
     Customized BERT Sequence Model
    '''
    def __init__(self, n_classes, model_name):
        #PRE_TRAINED_MODEL_NAME = 'bert-base-cased'
        super(PYBERTClassifier, self).__init__()
        if 'etri' in model_name or 'mecab' in model_name:
            self.bert = BertModel.from_pretrained(os.path.abspath('pytorch_model.bin'),
                                  output_hidden_states = False)
        else:
            self.bert = BertModel.from_pretrained(model_name)  # BERT 모델 불러오기

        #print(self.bert.config.hidden_size)

        self.drop = nn.Dropout(p=0.3)
        self.out = nn.Linear(self.bert.config.hidden_size, n_classes)

    def forward(self, input_ids, attention_mask):
        _, pooled_output = self.bert(
            input_ids=input_ids,  # tokenization이후 token id들의 리스트
            attention_mask=attention_mask  # 
        )
        #print(pooled_output.shape)

        output = self.drop(pooled_output)
        return self.out(output)

    def name(self):
        return 'PYBERTClassifier'

class PYBERTClassifierGenAtten(nn.Module):
    def __init__(self,
                 n_classes,
                 model_name,
                 dr_rate=None,
                 params=None):

        '''
        bert,
                 hidden_size=768,
                 num_classes=2,
                 dr_rate=None,
                 params=None
        '''

        super(PYBERTClassifierGenAtten, self).__init__()
        if 'etri' in model_name or 'mecab' in model_name:
            self.bert = BertModel.from_pretrained(os.path.abspath('pytorch_model.bin'),
                                                  output_hidden_states=False)
        else:
            self.bert = BertModel.from_pretrained(model_name)
        self.out = nn.Linear(self.bert.config.hidden_size, n_classes)
        self.dr_rate = dr_rate
        self.attention_mask=None

        if self.dr_rate != None:
            print('dropout ' + str(self.dr_rate))
            self.dropout = nn.Dropout(p=dr_rate)

    def gen_attention_mask(self, token_ids, targets):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(targets):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def get_attention_mask(self, atten_mask):
        self.attention_mask = atten_mask

    def forward(self, token_ids, targets, segment_ids, attention_mask):
        if attention_mask is None:
            self.attention_mask = self.gen_attention_mask(token_ids, targets)
        else:
            self.attention_mask = attention_mask

        _, pooler = self.bert(input_ids=token_ids,
                              token_type_ids=segment_ids.long(),
                              attention_mask=self.attention_mask.float().to(token_ids.device))

        if self.dr_rate:
            output = self.dropout(pooler)

        return self.out(output)

    def name(self):
        return 'PYBERTClassifierGenAtten'

class PYBertForSequenceClassification:
    '''
        Use pytorch's BERTForSeqeunceClassification
        Bert Model transformer with a sequence classification/regression head on top (a linear layer on top of the pooled output) e.g. for GLUE tasks.
        labels (torch.LongTensor of shape (batch_size,), optional, defaults to None)
        – Labels for computing the sequence classification/regression loss. Indices should be in [0, ..., config.num_labels - 1]. If config.num_labels == 1 a regression loss is computed (Mean-Square loss),
        If config.num_labels > 1 a classification loss is computed (Cross-Entropy).
    '''
    def __init__(self, n_classes, model_name):
        self.model = BertForSequenceClassification.from_pretrained(  # 감성 분류 용
                                    model_name,  # Use the 12-layer BERT model, with an uncased vocab.
                                    num_labels=n_classes,  # The number of output labels--2 for binary classification.
                                    # You can increase this for multi-class tasks.
                                    output_attentions=False,  # Whether the model returns attentions weights.
                                    output_hidden_states=False,  # Whether the model returns all hidden-states.
                                )
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        self.model.to(device)

    def __call__(self, *args, **kwargs):
        return self.model

    def name(self):
        return 'PYBertForSequenceClassification'

In [45]:
from transformers import BertForMaskedLM, BertModel, DistilBertForMaskedLM, DistilBertModel


def get_kobert_model():
    """ Return BertModel for Kobert """
    model = BertModel.from_pretrained("monologg/kobert")
    return model


def get_kobert_lm():
    """ Return BertForMaskedLM for Kobert """
    model = BertForMaskedLM.from_pretrained("monologg/kobert-lm")
    return model


def get_distilkobert_model():
    """ Return DistilBertModel for DistilKobert """
    model = DistilBertModel.from_pretrained("monologg/distilkobert")
    return model


def get_distilkobert_lm():
    """ Return DistilBertForMaskedLM for DistilKobert """
    model = DistilBertForMaskedLM.from_pretrained("monologg/distilkobert")
    return model

### Tokenization

input 데이터가 특정한 형식으로 입력되어야 함. 다음과 같은 형식들이 필요.

* [CLS]
* [SEP]
* Tokens : BERT 모델의 vocabulary에 존재하는 토큰 리스트
* Token IDs : BERT Tokenizer에서 나오는 토큰에 대한 정수 아이디
* Mask IDs : 토큰 시퀀스 중 어떤 요소가 문장에 존재하는 토큰이고 어떤 것이 padding element인지 나타내는 아이디
* Segment IDs : 문장 식별 아이디
* Positional Embeddings : 시퀀스 내에서 토큰의 위치를 표현

Transformer의 tokenizer.encode_plus함수가 위의 7개 정보를 처리

In [51]:
from transformers import BertTokenizer, BertModel
from load_kobert_model import get_kobert_model

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
#logging.basicConfig(level=logging.INFO)
from scipy.spatial.distance import cosine
import matplotlib.pyplot as plt

#import pytorch_pretrained_bert as ppb
import torch

#bert multi-lingual model
#https://github.com/google-research/bert/blob/master/multilingual.md

def get_pretrained_model(pretrained_type):
    if pretrained_type == 'etri':
        # use etri tokenizer
        print('not supported')
    elif pretrained_type == 'skt':
        # use gluonnlp tokenizer
        import gluonnlp as nlp
        vocab_path = './pretrained_model/skt/vocab.json'
        tokenizer_path = './pretrained_model/skt/tokenizer.model'
        vocab = nlp.vocab.BERTVocab.from_json(open(vocab_path, 'rt').read())
        tokenizer = nlp.data.BERTSPTokenizer(
            path=tokenizer_path, vocab=vocab, lower=False)
        vocab = tokenizer.vocab.token_to_idx
    elif pretrained_type == 'kobert':
        from tokenization_kobert import KoBertTokenizer
        tokenizer = KoBertTokenizer.from_pretrained('monologg/kobert')

    else:
        TypeError('Invalid pretrained model type')
    return tokenizer

#tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

tokenizer = get_pretrained_model('kobert') # 한국어 전용

In [58]:
text = "오늘은 하루종일 비가 와서 날씨가 흐리고 바람이 많이 불었습니다"

marked_text = "[CLS] " + text + " [SEP]"  # special token

# Tokenize our sentence with the BERT tokenizer.
tokenized_text = tokenizer.tokenize(marked_text)

# Print out the tokens.
print (tokenized_text) 

# WordPiece 임베딩을 사용하기 때문에 subwords, 글자 단위로 쪼개짐
# vocabulary에 존재하지 않는 단어들은 OOV또는 UNK 심볼로 처리되지 않고 subword나 낱글자로 쪼개져서 토큰화됨

['[CLS]', '▁오늘', '은', '▁하루', '종', '일', '▁비가', '▁', '와', '서', '▁날씨', '가', '▁흐', '리', '고', '▁바람', '이', '▁많이', '▁불', '었습니다', '[SEP]']


In [56]:
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)  # 토큰들을 vocabulary 인덱스로 매핑

for tup in zip(tokenized_text, indexed_tokens):
    print('{:<12} {:>6,}'.format(tup[0], tup[1]))

[CLS]             2
▁오늘           3,419
은             7,086
▁하루           4,937
종             7,268
일             7,126
▁비가           2,515
▁               517
와             6,983
서             6,553
▁날씨           1,408
가             5,330
▁흐            5,196
리             6,122
고             5,439
▁바람           2,195
이             7,096
▁많이           1,956
▁불            2,485
었습니다          6,890
[SEP]             3


In [57]:
segments_ids = [1] * len(tokenized_text)

print(segments_ids)  # 하나의 문장이라 모두 1로 표현됨

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [62]:
# 토큰화된 데이터를 torch tensors 구조로 변환

tokens_tensor = torch.tensor([indexed_tokens]) 
segments_tensors = torch.tensor([segments_ids])

print(tokens_tensor)
print(segments_tensors)

tensor([[   2, 3419, 7086, 4937, 7268, 7126, 2515,  517, 6983, 6553, 1408, 5330,
         5196, 6122, 5439, 2195, 7096, 1956, 2485, 6890,    3]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [63]:
model = BertModel.from_pretrained('bert-base-uncased',  # 인터넷으로부터 사전 학습된 모델을 가져옴
                                  output_hidden_states = True, # 모든 hidden state의 정보를 return
                                  )
model.eval()  # 평가 모드로 호출(학습이 끝난 후), 학습시 사용되는 dropout, regularization실행 x

# bert base uncased는 12개의 layer로 구성된 DNN

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [65]:
with torch.no_grad():
    outputs = model(tokens_tensor, segments_tensors)
    
# torch.no_grad’는 PyTorch에게 텍스트에 BERT모델을 적용하는 forward pass동안 완벽한 네트워크를 만들지 않도록 지도 하는데 사용함 
# 메모리 소비를 줄이고 속도 향상을 위해서

# Evaluating the model will return a different number of objects based on 
# how it's  configured in the `from_pretrained` call earlier. In this case, 
# becase we set `output_hidden_states = True`, the third item will be the 
# hidden states from all layers. See the documentation for more details:
# https://huggingface.co/transformers/model_doc/bert.html#bertmodel

hidden_states = outputs[2]


In [66]:
hidden_states

(tensor([[[ 0.1922, -0.6141, -0.4304,  ..., -0.0455, -0.2215,  0.3119],
          [ 0.0957, -0.5905, -0.4006,  ..., -0.0442, -0.0114,  0.3972],
          [ 0.3319,  0.5648, -0.4425,  ..., -0.1601,  0.9972, -1.3536],
          ...,
          [ 0.0883, -0.2967,  0.1458,  ..., -0.4173,  0.3155,  0.0045],
          [ 0.9272, -0.3361, -0.4502,  ..., -0.4800, -1.1224,  0.0485],
          [ 0.2557, -0.3528, -0.6428,  ...,  0.1651, -0.2962,  0.0377]]]),
 tensor([[[ 0.2560, -0.2960, -0.0824,  ...,  0.0641, -0.0085,  0.3444],
          [ 0.0902, -1.0775, -0.2841,  ...,  0.0472,  0.2717,  0.2524],
          [ 1.0793,  0.2208, -0.4960,  ..., -0.0100,  1.1624, -1.3039],
          ...,
          [ 0.2286, -0.4662,  0.6871,  ..., -0.7888,  0.6660,  0.1339],
          [ 1.1085, -0.6479, -0.3018,  ..., -0.5112, -1.0376, -0.2699],
          [ 0.3558, -0.3359, -0.0091,  ...,  0.3476,  0.0627, -0.1449]]]),
 tensor([[[ 0.1217, -0.4286,  0.0262,  ...,  0.1283,  0.0588,  0.2211],
          [-0.1001, -1.1888,

hidden_states에 저장된 정보는

* layer 수 : 13 (12개의 layer + word embedding layer)
* batch 수 : 1 (1문장)
* 단어/토큰 수 : 22 (예제 문장)
* Hidden unit의 수 : 768 (hidden embedding 차원, 자질의 수)

한 문장을 표현하기 위해 13*22*768=219648개의 고유한 값들이 존재

In [68]:
print ("Number of layers:", len(hidden_states), "  (initial embeddings + 12 BERT layers)")
layer_i = 0

print ("Number of batches:", len(hidden_states[layer_i]))
batch_i = 0

print ("Number of tokens:", len(hidden_states[layer_i][batch_i]))
token_i = 0

print ("Number of hidden units:", len(hidden_states[layer_i][batch_i][token_i]))


Number of layers: 13   (initial embeddings + 12 BERT layers)
Number of batches: 1
Number of tokens: 21
Number of hidden units: 768


In [71]:
# `hidden_states` is a Python list.
print('Type of hidden_states: ', type(hidden_states))

# Each layer in the list is a torch tensor.
print('Tensor shape for each layer: ', hidden_states[0].size()) # 하나의 문장에 22개의 단어가 존재하고, 각 단어는 768개의 차원으로 표현

Type of hidden_states:  <class 'tuple'>
Tensor shape for each layer:  torch.Size([1, 21, 768])


In [72]:
token_embeddings = torch.stack(hidden_states, dim=0)  # 모든 layer를 하나의 큰 tensor로 합침
token_embeddings.size()

torch.Size([13, 1, 21, 768])

In [73]:
token_embeddings = torch.squeeze(token_embeddings, dim=1)  # batch 차원은 필요 없어서 삭제 (1문장 밖에 없음)
token_embeddings.size()

torch.Size([13, 21, 768])

In [74]:
token_embeddings = token_embeddings.permute(1, 0, 2)  # layer, token의 위치를 변경
token_embeddings.size()

# 각 토큰은 13개의 768의 길이를 갖는 분리된 벡터들을 가짐
# 개별 단어를 만들기 위해서는 layer벡터 중 몇 개를 합치거나 하나만 선택 -> 어떤 layer를 선택할지, 어떤 layer들을 합쳐야할 지 결정해야 함

torch.Size([21, 13, 768])

In [75]:
# 방법1. 마지막 4개 layer를 concatenate (권장)

# Stores the token vectors, with shape [22 x 3,072 (4 x 768)]
token_vecs_cat = []
for token in token_embeddings:
    # `token` is a [12 x 768] tensor
    # Concatenate the vectors (that is, append them together) from the last four layers.
    # Each layer vector is 768 values, so `cat_vec` is length 3,072.
    cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)
    
    # Use `cat_vec` to represent `token`.
    token_vecs_cat.append(cat_vec)

print ('Shape is: %d x %d' % (len(token_vecs_cat), len(token_vecs_cat[0])))

Shape is: 21 x 3072


In [76]:
# 방법2. 마지막 4개 layer를 summing

token_vecs_sum = []
# `token_embeddings` is a [22 x 12 x 768] tensor.

# For each token in the sentence...
for token in token_embeddings:
    # `token` is a [12 x 768] tensor

    # Sum the vectors from the last four layers.
    sum_vec = torch.sum(token[-4:], dim=0)
    
    # Use `sum_vec` to represent `token`.
    token_vecs_sum.append(sum_vec)

print ('Shape is: %d x %d' % (len(token_vecs_sum), len(token_vecs_sum[0])))

Shape is: 21 x 768


In [77]:
# Sentence Vectors 만들기

token_vecs = hidden_states[-2][0]  # 각 토큰당 두 번째 부터 마지막 까지의 layer들의 평균

# Calculate the average of all 22 token vectors.
sentence_embedding = torch.mean(token_vecs, dim=0)

In [78]:
print ("Our final sentence embedding vector of shape:", sentence_embedding.size())  # 768 길이의 벡터 -> 문장들의 유사도를 계산할 수 있음

Our final sentence embedding vector of shape: torch.Size([768])


In [79]:
for i, token_str in enumerate(tokenized_text):
    print (i, token_str)

0 [CLS]
1 ▁오늘
2 은
3 ▁하루
4 종
5 일
6 ▁비가
7 ▁
8 와
9 서
10 ▁날씨
11 가
12 ▁흐
13 리
14 고
15 ▁바람
16 이
17 ▁많이
18 ▁불
19 었습니다
20 [SEP]


In [80]:
print('First 5 vector values for each instance of "bank".')
print('')
print("bank vault   ", str(token_vecs_sum[6][:5]))
print("bank robber  ", str(token_vecs_sum[10][:5]))
print("river bank   ", str(token_vecs_sum[19][:5]))

First 5 vector values for each instance of "bank".

bank vault    tensor([-0.5759, -0.3973,  1.3785,  0.7051, -0.9139])
bank robber   tensor([-0.0816,  2.6933,  0.4515,  2.2942, -2.6820])
river bank    tensor([ 1.3720, -0.1666,  0.5515, -0.2751, -1.7715])


In [81]:
from scipy.spatial.distance import cosine

diff_bank = 1 - cosine(token_vecs_sum[10], token_vecs_sum[19])
same_bank = 1 - cosine(token_vecs_sum[10], token_vecs_sum[6])

print('Vector similarity for  *similar*  meanings:  %.2f' % same_bank)
print('Vector similarity for *different* meanings:  %.2f' % diff_bank)

Vector similarity for  *similar*  meanings:  0.84
Vector similarity for *different* meanings:  0.78
